### ISSUE TITLE
User is reminded with notifications to finish their walk and if walk is still going after 2.5 hours it's automatically paused

### ISSUE THREAD

**Issue by brittmj** [sfbrigade/intentional-walk#100]
If recording has been running for 1 hour, send notification: “You've been walking for 1 hour. Don't forget to stop recording your walk if you're done!”

If recording has been running for 2 hours, send notification: “You've been walking for 2 hours. Your recorded walk will automatically pause in 30 minutes.”

If recording has been running for 2.5 hours, pause recording and send notification: "Your recorded walk has been paused. Please open the app and restart the walk if you're still walking."

When they open the app again their pause screen has a message on it about how the walk was auto paused: 
![Recording Walk - Auto Paused](https://user-images.githubusercontent.com/42448914/83429867-92927280-a3e9-11ea-9d66-97989b02eb4f.png)

**Comment by francisli** [comment]
@brittmj after evaluating two prior React Native notification libraries that didn't really work well, the third one's the charm and I'm starting to implement walk reminder notifications...

However, I'm realizing that right now the quickest way to implement this- so called "Local" notifications- do not allow the app to execute any code automatically when the notification is _shown_ (at least on iOS which I'm testing on first). The app does not "wake up" from the background unless the user explicitly "opens" the notification. This means I cannot automatically schedule a new unique follow-up notification, and cannot "pause" the walk after the last notification, if the user simply looks at and ignores the alert.

I can, on iOS, schedule the first notification to automatically repeat every hour. So if we change the message to be something generic, it can just continue to pop up every hour until the walk is stopped, i.e: “You've been walking for over an hour. Don't forget to stop recording your walk if you're done!”

For future reference: the only way on iOS that an app can deliver an alert in the background at a specific time AND execute some code is with a "Remote" notification, pushed from a server. This is a fair amount of additional setup/coordination with per-user server-side tracking.

I'm not sure what the latest capabilities/restrictions are with Android local scheduled notifications. Will update this issue once I get to testing on Android.

**Comment by brittmj** [comment]
Thanks for this detailed explanation.  This makes total sense, good to know for the future.  I like the idea of a notification reoccurring every hour that's not specific to how long you've been walking.

Is it still possible to auto pause a walk after it has been running for 2.5 hours if we don't connect the pausing action to how a user has responded to a notification? Or is pausing without the app being opened not possible at all?

**Comment by francisli** [comment]
The issue is that, once the phone is locked and the app is no longer active in the foreground, the OS is free to "suspend" or even terminate the app completely, to save on power/battery, memory, etc (this does not affect step tracking because that is already performed in the background by the OS). So the app by itself may not be running after 2.5 hours in a way that would allow it to pause the walk. The only way to "wake up" and start the app running, even just in the background, at least on iOS, is with the external server-delivered notification trigger.

**Comment by brittmj** [comment]
Ok, this makes sense.  I think the hourly reminders should be enough for this MVP.  Let's discuss on Wednesday, but it sounds like that's the best option right now.

**Comment by brittmj** [comment]
@francisli what does this hourly notification say? And does it need to be translated? I'm trying to inventory all the translation updates we still need

**Comment by francisli** [comment]
The exact string can be viewed here:

https://github.com/sfbrigade/intentional-walk/blob/d95aeb95afa0027a621872c3c8e345288f5fab17/lib/strings.js#L38

FYI, all the text is in that one file. If you scan through, you can see a few remaining English text strings in the Spanish and Chinese sections. Note that, if a translation is missing completely in the Spanish and Chinese sections (like the notification message string), the code falls back to the English version.
